= Python Code to invoke Robinhood API and Customize Display of Option History

:author: Sumiya
:nofooter:
:sectlinks:

== Goal
The History tab on Robinhood is not robust enough for me to analyze my own trading behavior.

I need a different way to slice and dice my trades and understand my trading psyche.

This write-up focuses on writing a script to fetch my Robinhood transaction history. I want to use API calls I can see from my browser, and begin customizing results in a manner I understand.

== What I Learnt?

Well, I thought the goal above would be a good use case to explore writing the code leveraging one of the many LLM/AI tools that exist today.

I chose Perplexity AI because it offers an anonymous prompter. And I had used it in the past for another TIL as part of my experiments with Rust, see here: https://github.com/psumiya/til/blob/main/rust/script-to-move-generated-rust-binary.adoc

=== Problem Breakdown
Here is how I broke down the problem:

* How would I invoke Robinhood APIs?
* Hoping a JSON response is returned, how would I parse the JSON response?
* How would I filter, format, and display the necessary results?

=== Prompts

==== Here is a view of the search session
* PDF View: link:search-session.pdf[]
* Perplexity Link: https://www.perplexity.ai/search/sample-code-to-Gzg53YXjSpCfx.bJD7kTFA

Here are the prompts, copied from the above search session that I tried along with my narration of what I was thinking as I asked these questions:

. sample code to read robinhood api
** This returned a 3rd party library based code, as well as using username and password. I was a little uncomfortable passing in credentials to a 3rd party library for this experiment.
. show me the same code but without using the robin_stocks dependency
** Now I could see some code that used Authorization headers. I decided to snag the necessary request headers from the network tab in browser's developer view, and export them as environment variables to connect to the APIs. That way I would not need to keep signing-in wioth my username/password and my experiments could just use the credentials from session on Robinhood.
** How do I view the response?
. also add code to print the current holdings
. also print history
** _This_ is what I am interested in.
. no do not use the robin_stocks library
** Almost admonished it for showing me the 3rd party library again
. python code to interact with robin hood api without using any 3rd party libraries
** To be extra sure, I repeated the instruction to show sample code without 3rd party libraries
. When I run above script I get NameError:name 'python' is not defined
** Yeah, I do not know Python.
. Show me the simplest python code I can run on mac
. For the robinhood api example you gave, I ran into an error, "ModuleNotFoundError: No module named 'requests'"
** `python3 -m pip install requests `
. How can I print the received response as formatted json
. how to read an environment variable
. create a method with a single parameter and print that parameter as a prettified json
** Slight re-factor to print JSON
. In the api response in json format I received an array of results. each element of the array has fields like state, chain_id, chain_symbol, opening_strategy, net_amount_direction, net_amount, updated_at.
. For a response like what I described, Filter by state == "filled"
Group by chain_id
create a table of chain_symbol, opening_strategy, net_amount_direction, net_amount
. Also sort the printed results within each group by reversed updated_at
. TypeError: unsupported format string passed to NoneType.__format__
** The prompt engine remembers the context and prints out an updated code.
. At the end of each chain group, for items in the group, print the total credit, total debit, and their diff
** The prompt engine thinks this is a new query, and forgets the context. I remind it again.
. No .. I mean in the response above where you grouped results by chain_id, there is a column for net_amount_direction. Use the value in the column such that you can print a total credit within a chained group by summing up values where total credit is sum when net_amount_direction is credit, total debit is sum when net_amount_direction is debit, and the diff is their difference.
. TypeError: unsupported operand type(s) for +=: 'int' and 'str'
. Keep the float rounded to 2 decimal points
. Now sum up the values of the diff you calculated across all chained groups and print the result. Keep the result to 2 decimal points.
. The results array is part of a paginated response from Robinhood. The paginated response has the following items: next, previous, results. The `next` item contains the API url we can use to get the next response. How do I repeat the above chained group calculations all the way until the `next` item is null?
. In addition to filtering for state == "filled", also filter out any data where updated_at is before September 2023
** I needed to limit the data to past 6 months.
. ValueError: Invalid isoformat string: '2024-03-25T15:10:57.063284Z'

=== Summary

Fun Fact, again: I do not know Python, yet!

What these LLM tools and this experiment shows is if you are looking to hack something together quickly for a domain you understand, but using tools (here, the specific programming language, python) you may not understand, the LLM _can_ be your ally.


Here is the final result I ended up with:

[source:python]
----
include::options.py[]
----


